"""empty message

Revision ID: 8c41b59efc7a
Revises: 
Create Date: 2018-10-02 08:23:41.992312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c41b59efc7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('username', sa.String(length=20), nullable=False))
    
    # ### end Alembic commands ###


#def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
